apiVersion: v1
kind: Service
metadata:
  name: simple-time-service-svc
spec:
  selector:
    app: simple-time-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: NodePort
